name       : metacity
version    : 3.34.1
release    : 11
source     :
    - https://download.gnome.org/sources/metacity/3.34/metacity-3.34.1.tar.xz : 31c7d1045c390afb3bf405735b0b26c459197cbf43af37c469eb8918ce3a453d
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - zenity
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
