name       : metacity
version    : 3.20.3
release    : 2
source     :
    - https://download.gnome.org/sources/metacity/3.20/metacity-3.20.3.tar.xz : 126ef860b0816b398b40173a3e1e562e71f96b7327906621f4baffb9ddfff3da
license    : GPL-2.0
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)    
    - pkgconfig(xft)
    - zenity    
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
