name       : metacity
version    : 3.36.0
release    : 12
source     :
    - https://download.gnome.org/sources/metacity/3.36/metacity-3.36.0.tar.xz : 260016cbb9287a434b557ee6c201fe2b138c5061879b816bf550c3d4873906a8
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - zenity
setup      : |
    %apply_patches
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
