name       : metacity
version    : 3.38.0
release    : 15
source     :
    - https://download.gnome.org/sources/metacity/3.38/metacity-3.38.0.tar.xz : 81193121b0d85dc93fef5701c00d0caf5313d10d9b19008403a4286cb04e11ac
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xpresent)
    - pkgconfig(xres)
    - zenity
setup      : |
    %apply_patches
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
