name       : metacity
version    : 3.22.1
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/metacity/3.22/metacity-3.22.1.tar.xz : d27d91864d8ba7294f6a093427ad16b20b1d834f4e23c9619bbeee6e641b5d87
license    : GPL-2.0
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - zenity
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
