name       : metacity
version    : 3.32.0
release    : 9
source     :
    - https://download.gnome.org/sources/metacity/3.32/metacity-3.32.0.tar.xz : 8f65b2cdc3587880d578b0f06e72922a3f90f2143691d9da7ceec7aac3aaed9c
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Window manager of GNOME Flashback.
description: |
    Window manager of GNOME Flashback.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - zenity
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
